const SECONDS_TO_MILLISECONDS = 1000;
const MINUTES_TO_SECONDS = 60;
const HOURS_TO_MINUTES = 60;
const DAY_TO_HOURS = 24;
const WEEK_TO_DAYS = 7;

const TASK_FILTER_TYPE = {
  ALL: 1,
  IMPORTANT: 2,
  DONE: 3,
  UNDONE: 4,
  DEAD_LINE: 5,
  DEAD_LINE_TODAY: 6,
  DEAD_LINE_ONE_WEEK: 7,
  DEAD_LINE_PASSED: 8,
};
